-- AlterTable
ALTER TABLE `transaction` ADD COLUMN `image` VARCHAR(191) NULL,
    ADD COLUMN `name` VARCHAR(191) NOT NULL DEFAULT 'transaction',
    MODIFY `type` ENUM('INCOME', 'EXPENSE') NOT NULL DEFAULT 'EXPENSE',
    MODIFY `amount` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    MODIFY `transactionDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
